### ISSUE TITLE
RF23: Eliminar empresa

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/Zeitgeist-Backend#13]
# Detalles
## UX/UI

![Image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105307730/e49ac0fa-96fd-4235-8e86-16124ca54c0e)

## User Story
Como administrador quiero dar de baja a una empresa en la plataforma para asegurar que solo las empresas activas estén presentes.

## Criterios de Aceptación
- [ ] El sistema permite al administrador buscar empresas por nombre para seleccionarlas para la baja.
- [ ] Al seleccionar una empresa para la baja, el sistema muestra una pantalla de confirmación antes de proceder.
- [ ] Una vez confirmada la baja, el sistema elimina la empresa y todas las relaciones con otras entidades de la plataforma.
- [ ] El sistema proporciona una confirmación visual en la plataforma de que la empresa ha sido dada de baja correctamente.

## Links a PRs

**Comment by salgue441** [comment]
Historia de usuario bloqueda, depende de tareas, proyectos y form
