### ISSUE TITLE
RF25: Crear tarea de un proyecto

### ISSUE THREAD

**Issue by sebFlores02** [Black-Dot-2024/Zeitgeist-Backend#22]
# Detalles
##UX/UI
![Image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105307730/e59dda2c-55a4-478a-949d-c844be2d5ccc)
## User Story
Como colaborador de un departamento quiero crear una nueva tarea de un proyecto para registrar una nueva actividad a realizar

## Criterios de Aceptación
- [ ] Al seleccionar la opción de registrar nueva tarea de un proyecto, el sistema muestra un formulario con datos a llenar sobre la nueva tarea: <ul>
    <li>Descripción</li>
    <li>Encargado</li>
    <li>Fecha de inicio</li>
    <li>Fecha de finalización</li>
    <li>Nombre</li>
    <li>Horas trabajadas</li>
    <li>Proyecto al que pertenece</li>
    <li>Estatus</li>
</ul>

- [ ] El sistema debe permitir al colaborador seleccionar la opción para guardar la información de la tarea y registrarla.
- [ ] Después de registrar la tarea, el sistema muestra un mensaje de éxito y actualiza las tareas.

## Links a PRs

**Comment by FridaBG** [comment]
Hola! Modifiqué un poquito los criterios de aceptación con la finalidad de que coincidan con la info que aparece en el diseño de Figma que ya está aprobado :)
