### ISSUE TITLE
RF12: Registrar nuevo proyecto

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/Zeitgeist-Backend#8]
# Detalles
## UX/UI
![Image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105307730/afaadb9d-8148-4280-9e43-791d695ac3e5)

## User Story
Como colaborador quiero registrar un nuevo proyecto para gestionar sus tareas y recursos.

## Criterios de Aceptación
- [ ] El sistema muestra al colaborador los proyectos activos.
- [ ] Al seleccionar la opción de registrar nuevo proyecto el sistema enseña un formulario con datos a llenar sobre el nuevo proyecto: <ul>
    <li>Nombre del proyecto</li>
    <li>Cliente</li>
    <li>Matter</li>
    <li>Categoría</li>
    <li>Fecha de inicio</li>
    <li>Fecha de finalización</li>
    <li>Descripción</li>
    <li>Cobrable</li>
    <li>Periódico</li>
    <li>Área (legal/accountable)</li>
</ul>

- [ ] El sistema debe validar que todos los campos estén completos y que sea del tipo especificado en el diccionario de datos.
- [ ] El sistema debe permitir al colaborador seleccionar la opción para guardar la información del proyecto y registrarlo.
- [ ] Después de registrar el proyecto, el sistema muestra un mensaje de éxito y actualiza los proyectos.

## Links a PRs

**Comment by FridaBG** [comment]
Hola! Modifiqué un poquito los criterios de aceptación con la finalidad de que coincidan con la info que aparece en el diseño de Figma que ya está aprobado :)
