### ISSUE TITLE
GH marca este error:

### ISSUE THREAD

**Issue by OlimpiaGarcia** [Black-Dot-2024/Zeitgeist-Backend#86]
GH marca este error: 

Property 'saveToken' does not exist on type '{ create: (entity: EmployeeEntity) => Promise<EmployeeEntity>; findAll: () => Promise<EmployeeEntity[]>; findByEmail: (email: string) => Promise<...>; findById: (id: string) => Promise<...>; existByEmail: (email: string) => Promise<...>; updateRoleById: (id: string, roleId: string) => Promise<...>; }'.

_Originally posted by @OlimpiaGarcia in https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/71#discussion_r1577328058_

**Comment by dembA7** [comment]
resuelto
