### ISSUE TITLE
En el req.auth.data, se encuentra la info del employee. Ahi se encuentra el email

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/Zeitgeist-Backend#87]
En el req.auth.data, se encuentra la info del employee. Ahi se encuentra el email

_Originally posted by @DHurtado714-itesm in https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/71#discussion_r1579818129_

**Comment by dembA7** [comment]
corregido
