### ISSUE TITLE
RF20: Consultar reporte de proyecto

### ISSUE THREAD

**Issue by lCDSLl-Richard** [Black-Dot-2024/Zeitgeist-Backend#9]
# Detalles
## UX/UI
![Image](https://github.com/Black-Dot-2024/Zeitgeist-Backend/assets/105307730/ce1b9402-815d-4357-9595-6b0c2ce441b1)

## User Story
Como colaborador quiero consultar el reporte completo de un proyecto para conocer el trabajo que se hizo para un cliente.

## Criterios de Aceptación
- [x] El sistema valida la información del proyecto al que quiere hacer un reporte.
- [x] El sistema muestra la siguiente información para un proyecto <ul>
    <li>Cliente/Empresa</li>
    <li>Matter</li>
    <li>Category</li>
    <li>Area</li>
    <li>Chargeable</li>
    <li>Start Day</li>
    <li>Due Date</li>
    <li>
        Tareas relacionadas al proyecto
        <ul>
            <li>Nombre de la tarea</li>
            <li>Descripción</li>
            <li>Status</li>
            <li>Horas</li>
            <li>Responsable</li>
            <li>Start Day</li>
            <li>Due Day</li>
        </ul>
    </li>
    <li>Gráfica</li>
</ul>

## Links a PRs

**Comment by FridaBG** [comment]
Hola! Modifiqué un poquito los criterios de aceptación con lo que me preguntaron la semana pasada de la edición de un reporte.

No se preocupen por el estatus actual de los proyectos, ya sea "en cotización" o "aceptado". Al final del día, se mostrará en el reporte la información disponible de cada proyecto, independientemente de su estatus.
