### ISSUE TITLE
No usar console.error, mejor usar throw new. De por si el repository ya lanza el error, entonces no es necesario

### ISSUE THREAD

**Issue by DHurtado714-itesm** [Black-Dot-2024/Zeitgeist-Backend#90]
No usar console.error, mejor usar throw new. De por si el repository ya lanza el error, entonces no es necesario

_Originally posted by @DHurtado714-itesm in https://github.com/Black-Dot-2024/Zeitgeist-Backend/pull/71#discussion_r1579820044_

**Comment by dembA7** [comment]
corregido
